### ISSUE TITLE
Error in App Registration after update 13.0.5

### ISSUE THREAD

**Issue by nagodoy** [pellaeon/registration#147] opened 2018-08-06 13:04 UTC
OCP\AppFramework\Db\MultipleObjectsReturnedException: Did not expect more than one result when executing: query "SELECT * FROM `*PREFIX*registration` WHERE `email` = ? "; parameters Array ( [0] => xxxx@xxx.xxx.xx) ; limit ""; offset ""

    /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php - line 359: OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)
    /var/www/nextcloud/apps/registration/db/registrationmapper.php - line 72: OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM `...', Array)
    /var/www/nextcloud/apps/registration/service/registrationservice.php - line 159: OCA\Registration\Db\RegistrationMapper->find('nagodoy@uol.com...')
    /var/www/nextcloud/apps/registration/controller/registercontroller.php - line 84: OCA\Registration\Service\RegistrationService->validateEmail('nagodoy@uol.com...')
    [internal function] OCA\Registration\Controller\RegisterController->validateEmail('nagodoy@uol.com...')
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Registration\Controller\RegisterController), 'validateEmail')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Registration\Controller\RegisterController), 'validateEmail')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Registratio...', 'validateEmail', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 999: OC\Route\Router->match('/apps/registrat...')
    /var/www/nextcloud/index.php - line 42: OC handleRequest()
    {main}

**Comment by pellaeon** [comment] 2018-08-06 16:41
This is due to, for some reason, there exist more than 1 pending registration in the database. I'm not sure how that happened, if you could provide some hint on what steps you took to reach this state it would be helpful.
Otherwise, you could just drop the entire `*PREFIX*registration` table. (all pending registration will be lost)

I'm closing this for now, unless you could let me know how to reproduce this bug.

**Closed by pellaeon** 2018-08-06 16:41 UTC
