### ISSUE TITLE
Register Login page offet

### ISSUE THREAD

**Issue by PaulterTV** [pellaeon/registration#194] opened 2020-01-28 21:25 UTC
### Steps to reproduce
1. Main Login page @my server

### Expected behaviour
Register Button should be in the middle

### Actual behaviour
Register Button has an offset.

### Server configuration
**Operating system**: Ubuntu 19.10 (GNU/Linux 5.3.0-26-generic x86_64)

**Web server:** Apache2

**Database:** mysql  Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))

**PHP version:** PHP 7.3.11-0ubuntu0.19.10.2 (cli) (built: Jan 14 2020 15:33:46)

**Nextcloud version:** 18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install. 2 Days ago

**Where did you install Nextcloud from:** my personal Webserver

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - audioplayer: 2.9.0
  - bruteforcesettings: 1.5.0
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_downloadactivity: 1.7.0
  - files_linkeditor: 1.0.11
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.1.6
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - rainloop: 6.0.6
  - recommendations: 0.6.0
  - registration: 0.4.7
  - richdocuments: 3.5.1
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 1.0.6
  - socialsharing_twitter: 1.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - uploaddetails: 0.1.2
  - video_converter: 0.1.3
  - viewer: 1.2.0
  - weather: 1.6.4
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - breezedark
  - encryption
  - files_external
  - flowupload
  - quicknotes
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.170",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "http:\/\/192.168.2.170\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "breezedark",
            "files_ebookreader",
            "weather",
            "uploaddetails",
            "socialsharing_twitter",
            "socialsharing_email"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome, Firefox, Opera

**Operating system:** Windows 10 / 7

### Logs
// Not needed
![Capture](https://user-images.githubusercontent.com/60407496/73306582-ca5f9280-421c-11ea-927f-84d101119d10.PNG)

**Comment by angelfor3v3r** [comment] 2020-01-31 05:04
Same issue here. Seems to have happened after I updated to 18.0.0

**Comment by deafgaminghd** [comment] 2020-02-02 20:13
Same issues here. It was after i update nextcloud 18.0.0 

Thank you, 
Richard Applegate

**Comment by Derkades** [comment] 2020-02-04 20:34
Duplicate of #191

**Comment by ExittOnly** [comment] 2020-02-06 21:47
Yep, same issue here. 

![image](https://user-images.githubusercontent.com/60555640/73981498-4bdfb080-4900-11ea-93f6-4ad45bcf1bf5.png)

**Comment by pellaeon** [comment] 2020-02-07 12:32
Seems that this is a problem from the Nextcloud core stylesheets, which is fixed here: https://github.com/nextcloud/server/pull/19238

Please test, or wait for the next server release.

**Closed by pellaeon** 2020-02-07 12:32 UTC
