### ISSUE TITLE
Ability to request an activation by an admin (like "request account" feature)

### ISSUE THREAD

**Issue by Ich5003** [pellaeon/registration#120] opened 2018-01-14 12:22 UTC
Hello,

//EDIT: I just realized this is a duplicate of one of the oldest requests (#2). Sorry

this is not a bug report, it's more like a feature request (I hope it's okay to post it here).
I would love if this App would add one of the following registration procedures:

1. This would be the most awesome feature.
• The user enters his E-Mail-Address and his full name.
• A verification E-Mail is sent to the given address.
• After user verified his mail an admin account is notified and he needs to accept this registration (and set a username)
• User get's an email his account is now enabled.

2. 
• Registration progress is normal, as it is now.
• But: User is disabled by default (you can enable/disable users via occ).
• Admin needs to manually enable the disabled user.

Behaviour may change, but it would be awesome if it's similar to this description above.
If you won't add one of those features, it's okay too, then I may try to use the existing code and change it for my own needs.

Thank you,
Lucas

**Comment by tobiasnix** [comment] 2018-01-19 08:23
This seems like a duplicate of #2

**Comment by pellaeon** [comment] 2018-02-23 07:36
Closing in favor of #2

**Closed by pellaeon** 2018-02-23 07:36 UTC
