### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by oCa-flash** [pellaeon/registration#96] opened 2017-09-03 05:51 UTC
Good afternoon!

The application Registration is installed. When you click on the "Register" button, you receive a message:

Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 31.128.42.172
Request ID: S2gZzU9gVyc8fw2Glc0A

Data on my server:
Ubuntu Server 16.04
LAMP
Nextcloud version 11.0.4 is installed via snap

sudo -u www-data php occapp: list
. $ SNAP / utilities / mysql-utilities
. $ SNAP / utilities / php-utilities
. $ SNAP / utilities / redis-utilities
. $ SNAP / utilities / nextcloud-utilities

LDAP not used

/index.php/settings/integrity/failed
No errors have been found.

log:
{"reqId":"key","remoteAddr":"31.128.42.172","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve registrationService! Class registrationService does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('registrationSer...')\\n#1 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('registrationSer...')\\n#2 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(73): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('registrationSer...')\\n#3 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Registratio...')\\n#5 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Registratio...')\\n#6 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(101): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('OCA\\\\\\\\Registratio...')\\n#7 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Registratio...', 'askEmail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/base.php(1012): OC\\\\Route\\\\Router->match('\\\/apps\\\/registrat...')\\n#11 \\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/snap\\\/nextcloud\\\/2707\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","level":3,"time":"2017-09-03T05:57:04+00:00","method":"GET","url":"\/index.php\/apps\/registration\/","user":"user","version":"11.0.4.1"}

**Comment by Raiderpoer** [comment] 2017-09-07 01:18
I've got the same...

**Comment by pellaeon** [comment] 2017-09-07 04:42
duplicate of #95

**Closed by pellaeon** 2017-09-07 04:42 UTC
