### ISSUE TITLE
A problem occurred sending email, please contact your administrator

### ISSUE THREAD

**Issue by linamu** [pellaeon/registration#38] opened 2016-03-11 13:05 UTC
i got this problem "A problem occurred sending email, please contact your administrator."
when i press 'request verification link'

**Comment by pellaeon** [comment] 2016-03-17 13:24
I think I may have found the error, could you re-fill this issue report according to the[ issue template](https://github.com/owncloud/core/blob/master/issue_template.md)?

**Comment by yavama** [comment] 2016-03-17 13:33
Operating system: ubuntu 14.04
Web server: lamp server
Database: mysql
PHP version: PHP 5.5.9
ownCloud version: 9.0.0
fresh install
Where did you install ownCloud from: owncloud.org
Signing status (ownCloud 9.0 and above): No errors have been found.
List of activated apps:
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - logreader: 1.1.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - registration: 0.1.3
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
The content of config/config.php:
{
    "system": {
        "instanceid": "oc40h6cge2hn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/127.0.0.1\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "wiemjaouadi",
        "mail_smtpmode": "php",
        "mail_domain": "gmail.com"
    }
}

**Comment by pellaeon** [comment] 2016-03-17 13:39
@yavama thanks, I pushed a fix to `pr-fix-sendValidationEmail` branch, could you test it?

**Comment by yavama** [comment] 2016-03-17 13:43
i have the same error

**Comment by pellaeon** [comment] 2016-03-17 13:46
and the logs?

**Comment by yavama** [comment] 2016-03-17 13:47
what logs?

**Comment by pellaeon** [comment] 2016-03-17 13:48
owncloud.log

**Comment by yavama** [comment] 2016-03-17 13:48
{"reqId":"VHJjtdL9A9U\/vCs3iFKg","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_dhouhadhouha\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'owncloud'@'localhost' for table 'user'","level":3,"time":"2016-03-15T10:58:45+00:00"}
{"reqId":"VHJjtdL9A9U\/vCs3iFKg","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `owncloud` . * TO 'owncloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'owncloud'@'localhost' to database 'owncloud'","level":3,"time":"2016-03-15T10:58:45+00:00"}
{"reqId":"VHJjtdL9A9U\/vCs3iFKg","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/html\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-15T10:58:45+00:00"}
{"reqId":"UROmV2wRYHpqTL24YLnh","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_dhouhadhouha\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'ownclouduser'@'localhost' for table 'user'","level":3,"time":"2016-03-15T14:07:38+00:00"}
{"reqId":"UROmV2wRYHpqTL24YLnh","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'CREATE DATABASE IF NOT EXISTS `owncloud` CHARACTER SET utf8 COLLATE utf8_bin;':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'ownclouduser'@'localhost' to database 'owncloud'","level":3,"time":"2016-03-15T14:07:38+00:00"}
{"reqId":"UROmV2wRYHpqTL24YLnh","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/html\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-15T14:07:38+00:00"}
{"reqId":"JWOA8TtbNBQnlPYXieXt","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_dhouhadhouha\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'owncloud'@'localhost' for table 'user'","level":3,"time":"2016-03-17T09:22:34+00:00"}
{"reqId":"JWOA8TtbNBQnlPYXieXt","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `owncloud` . * TO 'owncloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'owncloud'@'localhost' to database 'owncloud'","level":3,"time":"2016-03-17T09:22:34+00:00"}
{"reqId":"JWOA8TtbNBQnlPYXieXt","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/html\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-17T09:22:34+00:00"}
{"reqId":"\/V2gwZXrwyT6QMIlTVkS","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_dhouhadhouha\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'ownclouduser'@'localhost' for table 'user'","level":3,"time":"2016-03-17T09:37:59+00:00"}
{"reqId":"\/V2gwZXrwyT6QMIlTVkS","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `ownclouddb` . * TO 'ownclouduser'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'ownclouduser'@'localhost' to database 'ownclouddb'","level":3,"time":"2016-03-17T09:37:59+00:00"}
{"reqId":"\/V2gwZXrwyT6QMIlTVkS","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/html\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-17T09:37:59+00:00"}
{"reqId":"\/V2gwZXrwyT6QMIlTVkS","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/html\\\/o...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/html\\\/o...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-17T09:38:04+00:00"}
{"reqId":"\/V2gwZXrwyT6QMIlTVkS","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/html\\\/o...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/html\\\/o...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-17T09:38:05+00:00"}
{"reqId":"hj9iaTH2xx9e07llYRIw","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 135 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:43:32+00:00"}
{"reqId":"hj9iaTH2xx9e07llYRIw","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 135 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:43:32+00:00"}
{"reqId":"fHwL5u+22OBQi7CCI7+Q","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T09:43:46+00:00"}
{"reqId":"40N2ZuSJm33m1kGMyW3\/","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T09:46:16+00:00"}
{"reqId":"NUFhtUFD9YWS7ayJJsD\/","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:47:04+00:00"}
{"reqId":"NUFhtUFD9YWS7ayJJsD\/","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:47:04+00:00"}
{"reqId":"halD4nlZ0OhvBWjvOWNS","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 135 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:47:17+00:00"}
{"reqId":"halD4nlZ0OhvBWjvOWNS","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 135 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:47:17+00:00"}
{"reqId":"Ybq8o0uMefjXO7r8l+dY","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:47:26+00:00"}
{"reqId":"Ybq8o0uMefjXO7r8l+dY","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:47:26+00:00"}
{"reqId":"I0Dathv3DquBLKdLnXNl","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T09:47:44+00:00"}
{"reqId":"uuaZuXa1S9yF2xnDxOex","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:48:20+00:00"}
{"reqId":"uuaZuXa1S9yF2xnDxOex","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:48:20+00:00"}
{"reqId":"ekZTJUGtOhqrTKwEvQQZ","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T09:54:13+00:00"}
{"reqId":"+wSBIR7d\/cUn7fxW4J63","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 135 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:59:21+00:00"}
{"reqId":"+wSBIR7d\/cUn7fxW4J63","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 135 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T09:59:21+00:00"}
{"reqId":"vzTzpoRvEPqhuKW2Us\/I","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T10:30:05+00:00"}
{"reqId":"vzTzpoRvEPqhuKW2Us\/I","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T10:30:05+00:00"}
{"reqId":"bq3LaPpLas3H32btKaZW","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T13:40:43+00:00"}
{"reqId":"rRv7ErrMpT1\/KAMOavkV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T13:40:48+00:00"}
{"reqId":"rpFBIzx3oQpKQDSlPpAr","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:41:25+00:00"}
{"reqId":"rpFBIzx3oQpKQDSlPpAr","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:41:25+00:00"}
{"reqId":"4sfkomYvSqCgFwHWfAVU","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:41:33+00:00"}
{"reqId":"4sfkomYvSqCgFwHWfAVU","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:41:33+00:00"}
{"reqId":"0pLJnhM4G6M3uYrnqpsw","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:41:43+00:00"}
{"reqId":"0pLJnhM4G6M3uYrnqpsw","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:41:43+00:00"}
{"reqId":"L3RCvGssB+4XReyJbA2L","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:42:25+00:00"}
{"reqId":"L3RCvGssB+4XReyJbA2L","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Registration\\Controller\\RegisterController::sendValidationEmail() must be an instance of OCA\\Registration\\Controller\\string, string given, called in \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php on line 84 and defined at \/var\/www\/html\/owncloud\/apps\/registration\/controller\/registercontroller.php#267","level":3,"time":"2016-03-17T13:42:25+00:00"}
{"reqId":"JEVRt9fmTVShABS54bJH","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-17T13:47:06+00:00"}

**Comment by pellaeon** [comment] 2016-03-17 14:14
Could you make sure line 267 of `controller/registercontroller.php` looks exactly like this? :
`private function sendValidationEmail(\string $token, \string $to) {`

**Comment by yavama** [comment] 2016-03-17 14:17
here it is : private function sendValidationEmail(string $token, string $to) {

**Comment by pellaeon** [comment] 2016-03-17 14:19
Please modify it to `private function sendValidationEmail(\string $token, \string $to) {` and test again.

**Comment by yavama** [comment] 2016-03-17 14:21
i still have the same error :/

**Comment by pellaeon** [comment] 2016-03-17 14:27
Do you mean error on the web page or in owncloud.log ?
If you haven't checked the log, please provide relevant (newest) entries. (NOT the entire log file!)

**Comment by yavama** [comment] 2016-03-17 14:29
error in the web page, i got this whenever i press the verification link button "A problem occurred sending email, please contact your administrator."

**Comment by pellaeon** [comment] 2016-03-17 14:30
Please provide relevant (newest) entries. (NOT the entire log file!)

**Comment by yavama** [comment] 2016-03-17 14:31
Error	PHP	Undefined index: newVersionString at /var/www/html/owncloud/apps/updatenotification/templates/admin.php#8	a few seconds ago
Error	PHP

**Comment by pellaeon** [comment] 2016-03-17 14:32
That is not a relevant entry, it should have something to do with registration.

**Comment by yavama** [comment] 2016-03-17 14:33
![screenshot from 2016-03-17 15 32 50](https://cloud.githubusercontent.com/assets/17200559/13849251/95b5abc6-ec55-11e5-8e5a-78b92cdebf10.png)

**Comment by pellaeon** [comment] 2016-03-17 14:36
I'm gonna need some time to investigate.

**Comment by yavama** [comment] 2016-03-20 15:49
any news ?

**Comment by ToggoStar** [comment] 2016-05-30 12:14
I have the same issue - any ideas?

**Comment by pellaeon** [comment] 2016-05-30 12:19
@ToggoStar "Problem sending email" is a generic error message, you are not having the same issue as this thread unless you have the same `sendEmailValidation() must be a instance of string, string given...` error.

**Comment by ToggoStar** [comment] 2016-05-30 16:09
I have the same error messages as linamu posted in the screenshot above! ("Argument 1 passed..." and "Argument 2 passed...")

**Comment by pellaeon** [comment] 2016-05-31 11:56
@ToggoStar Could you also post you system information, same as linamu?

**Comment by ToggoStar** [comment] 2016-05-31 12:10
@pellaeon I am running ownCloud on a webserver provided by Host Europe, so I don't know all the details of the server. What I do know:

Database: MySQL
PHP: Version 5.6
ownCloud: Version 9.0.1
Fresh install
Installed from owncloud.org
Signing status: No errors
Activated apps:

activity 2.2.1
collaborative tags 0.2
comments 0.2
deleted files 0.8.0
federation: 0.0.4
gallery 14.5.0
mail template editor 0.1
notifications 0.2.3
pdf viewer 0.8
provisioning api 0.4.1
share files 0.9.1
text editor 2.1
update notification 0.1.0
versions 1.2.0
video player 0.9.8
documents 0.12.0

The content of config.php:

<?php
$CONFIG = array (
  'instanceid' => 'ocibz2majmv1',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'wp12245163.server-he.de',
  ),
  'datadirectory' => '/is/htdocs/wp12245163_6QIX53A9QL/www/owncloud/data',
  'overwrite.cli.url' => 'https://wp12245163.server-he.de/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'db12245163-owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
);

I hope this helps! :)

**Comment by ToggoStar** [comment] 2016-06-07 11:13
@pellaeon Any news on this issue? Is there anything I can do to help?

**Comment by pellaeon** [comment] 2016-06-26 07:44
Fixed via 20bb451

**Closed by pellaeon** 2016-06-26 07:44 UTC

**Comment by pellaeon** [comment] 2016-06-30 07:02
@ToggoStar @linamu there are still reports of this bug being present, could you verify if it is actually fixed?

**Comment by ToggoStar** [comment] 2016-06-30 08:06
@pellaeon I switched to a different server recently and there the issue is gone, however I can't tell if it is because of your fix or because of switching servers... :/

**Comment by pellaeon** [comment] 2016-06-30 08:09
This problem probably only occur on PHP 5.6 and below, is your new server
PHP 7 ?

2016-06-30 16:06 GMT+08:00 ToggoStar <notifications@github.com>:

**Comment by ToggoStar** [comment] 2016-06-30 09:08
It's on 5.5!

**Comment by pellaeon** [comment] 2016-06-30 09:12
Hmm, then the problem is probably fixed, I'll see if there are future
complaints.

2016-06-30 17:08 GMT+08:00 ToggoStar <notifications@github.com>:
