### ISSUE TITLE
Feature Request: Add Recaptcha into Registration Page

### ISSUE THREAD

**Issue by iamdoubz** [pellaeon/registration#207] opened 2020-05-20 18:29 UTC
# Steps to reproduce
1. Click Register
2. Enter email address
3. Complete Recaptcha response to prevent spam accounts from generating

### Expected behaviour
Recaptcha shows on registration page.

### Actual behaviour
Feature request.

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache2

**Database:** MySQL 5.7.30

**PHP version:** 7.3.17

**Nextcloud version:** (see Nextcloud admin page) 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** N/A

**Where did you install Nextcloud from:** N/A

**Signing status:**
<details>
<summary>Signing status</summary>

```
N/A
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - data_request: 1.5.0
  - dav: 1.14.0
  - drawio: 0.9.5
  - encryption: 2.6.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.5
  - news: 14.1.7
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - piwik: 0.5.4
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - registration: 0.4.7
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - apporder
  - files_external
  - metadata
  - social
  - socialsharing_diaspora
  - socialsharing_email
  - socialsharing_facebook
  - socialsharing_twitter
  - unsplash
  - uploaddetails
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... No.

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No.

### Client configuration
**Browser:** Chrome 81, Edge 81

**Operating system:**

### Logs
N/A

### Additional
Ideally, in the Registration settings, add ability to choose v2 or v3 Google reCaptcha and/or another non-Google recaptcha for the Registration page only.

Thank you for a great app!

**Comment by pellaeon** [comment] 2020-05-28 05:08
Duplicate of #11

**Closed by pellaeon** 2020-05-28 05:08 UTC
