### ISSUE TITLE
How can i deactivate the screen "Registration is only allowed for the following domains: "

### ISSUE THREAD

**Issue by F3000** [pellaeon/registration#188] opened 2019-12-09 12:00 UTC
Hi , 

is it possible to deactivate this screen ? So a user who is not allowed to register, cant see which domains are allowed. 

![Unbenannt](https://user-images.githubusercontent.com/8161283/70434192-d84a3000-1a83-11ea-98da-95e83234ef09.png)

**Comment by anemanic** [comment] 2020-01-29 22:49
Yes, this is major, please enable possibility to hide list of domains.

**Comment by pellaeon** [comment] 2020-02-07 12:33
I'll list this as an enhancement, pull requests welcome.

**Comment by pellaeon** [comment] 2020-02-07 12:34
Duplicate of #119

**Closed by pellaeon** 2020-02-07 12:34 UTC
Labels: enhancement
